version: '3.5'
networks: 
    default:
        name: dynamodb
        driver: bridge

services: 
    dynamodb:
        container_name: ${CONTAINER_NAME}
        image: amazon/dynamodb-local
        privileged: true
        tty: true
        networks: 
            default: 
                aliases:
                    - ${CONTAINER_NAME}
                    - dynamodb
        restart: "no"
        ports: 
            - "6509:8000"