version: '3'
networks: 
    dbs:
        external: 
            name: ${DB_NETWORK}

volumes: 
    sonarqube_data:
        external: false
    sonarqube_temp:
        external: false
    sonarqube_logs:
        external: false
    sonarqube_extensions:
        external: false

services: 
    sonarqube:
        container_name: ${CONTAINER_NAME}
        image: sonarqube:8.4.2-community
        privileged: true
        tty: true
        environment:
            SONAR_JDBC_URL: ${DB_JDBC_LINK}
            SONAR_JDBC_USERNAME: ${DB_USER}
            SONAR_JDBC_PASSWORD: ${DB_PASSWORD}
        volumes:
            - 'sonarqube_extensions:/opt/sonarqube/extensions'
            - 'sonarqube_data:/opt/sonarqube/data'
            - 'sonarqube_logs:/opt/sonarqube/logs'
            - 'sonarqube_temp:/opt/sonarqube/temp'
        networks: 
            - dbs
        restart: "no"
        ports:
            - "9000:9000"