version: "3.5"
networks:  
  default:
    name: stardog
    driver: bridge
services: 
  stardog:
    container_name: ${CONTAINER_NAME}
    image: stardog/stardog:latest
    privileged: true
    tty: true
    environment:
      - "STARDOG_SERVER_JAVA_ARGS=-Xmx8g -Xms8g -XX:MaxDirectMemorySize=12g"
    networks: 
      default: 
        aliases:
          - ${CONTAINER_NAME}
          - stardog
    restart: "no"
    ports: 
      - "5820:5820"
    volumes:
      - ${STARDOG_HOME}:/var/opt/stardog

