version: '3.5'
networks: 
    default:
        name: rabbitmq
        driver: bridge

services: 
    rabbitmq:
        container_name: ${CONTAINER_NAME}
        image: rabbitmq:management
        privileged: true
        tty: true
        networks: 
            default: 
                aliases:
                    - ${CONTAINER_NAME}
        restart: "no"
        ports: 
            - 5672:5672
            - 15672:15672