version: '3.5'
networks:
    jenkins:
        name: ${DEFAULT_NETWORK_NAME}
        driver: bridge
    sonarqube:
        external: 
            name: ${SONARQUBE_NETWORK}
volumes: 
    jenkins-docker-certs:
        external: false
    jenkins-data:
        external: false
services:
    jenkins_docker:
        container_name: ${CONTAINER_DOCKER_NAME}
        image: docker:dind
        privileged: true
        networks:
            jenkins:
                aliases: 
                    - ${CONTAINER_DOCKER_NAME}
        environment: 
            - DOCKER_TLS_CERTDIR=/certs
        volumes: 
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
        ports: 
            - "${JENKINS_DOCKER_HOST_PORT}:2376"
        #restart: "no"
        tty: true
    jenkins:
        container_name: ${CONTAINER_SERVER_NAME}
        image: jenkinsci/blueocean
        networks: 
            jenkins:
                aliases: 
                    - ${CONTAINER_SERVER_NAME}
            sonarqube:
        environment: 
            - DOCKER_HOST=tcp://${CONTAINER_SERVER_NAME}:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        ports: 
            - "${JENKINS_WEB_HOST_PORT}:8080"
            - "${JENKINS_SLAVE_SERVERS_HOST_PORT}:50000"
        volumes: 
            - jenkins-docker-certs:/certs/client:ro
            - jenkins-data:/var/jenkins_home
        tty: true